-- DELETE FROM pizza_sales
-- WHERE pizza_id = 'pizza_id';
-- SELECT * FROM pizza_sales;
-- ALTER TABLE pizza_sales
-- ALTER COLUMN pizza_id TYPE INTEGER using pizza_id::integer
-- ALTER COLUMN order_id TYPE INTEGER using order_id::integer;
-- ALTER COLUMN quantity TYPE INTEGER using quantity::integer;
-- ALTER COLUMN order_date TYPE DATE using order_date::date;
-- ALTER COLUMN order_time TYPE TIME using order_time::time;
-- ALTER COLUMN unit_price TYPE FLOAT using unit_price::double precision;
-- ALTER COLUMN total_price TYPE FLOAT using total_price::double precision;
-- SELECT * FROM information_schema.COLUMNS WHERE TABLE_NAME='pizza_sales';